import type { ModularActionDefinition } from "../../modularActions";

export const definition: ModularActionDefinition = {
  id: "string_ops",
  version: "1.0.0",
  name: "String Ops",
  description: "String operations: split/join/replace/substring/contains/trim/case/length.",
  category: "utility",
  tags: ["string", "transform"],
  inputs: [
    {
      name: "operation",
      type: "string",
      default: "split",
      options: [
        { value: "split", label: "split" },
        { value: "join", label: "join" },
        { value: "replace", label: "replace" },
        { value: "substring", label: "substring" },
        { value: "contains", label: "contains" },
        { value: "trim", label: "trim" },
        { value: "to_upper", label: "to_upper" },
        { value: "to_lower", label: "to_lower" },
        { value: "length", label: "length" },
      ],
      description: "Operation type.",
    },
    {
      name: "value",
      type: "string",
      default: "",
      description: "Source value.",
    },
    {
      name: "items",
      type: "string",
      default: "",
      description: "Optional array input for join (supports array or JSON string).",
    },
    {
      name: "delimiter",
      type: "string",
      default: ",",
      description: "Delimiter used by split (and CSV fallback for join).",
    },
    {
      name: "joiner",
      type: "string",
      default: ",",
      description: "Join separator.",
    },
    {
      name: "search",
      type: "string",
      default: "",
      description: "Search text for replace/contains.",
    },
    {
      name: "replace_with",
      type: "string",
      default: "",
      description: "Replacement text for replace.",
    },
    {
      name: "start",
      type: "integer",
      default: 0,
      description: "Start index for substring.",
    },
    {
      name: "end",
      type: "integer",
      default: -1,
      description: "End index for substring. -1 means to end.",
    },
    {
      name: "case_sensitive",
      type: "boolean",
      default: true,
      description: "Whether replace/contains is case-sensitive.",
    },
  ],
  outputs: [
    { name: "result", type: "any", description: "Operation result." },
    { name: "text", type: "string", description: "String representation result." },
    { name: "items", type: "any", description: "Array result, when applicable." },
    { name: "contains", type: "boolean", description: "Contains check result." },
    { name: "length", type: "integer", description: "String/array length." },
  ],
  i18n: {
    name: { "zh-CN": "\u5b57\u7b26\u4e32\u5904\u7406", "en-US": "String Ops" },
    description: {
      "zh-CN": "\u5b57\u7b26\u4e32\u64cd\u4f5c\uff1asplit/join/replace/substring/contains \u7b49\u3002",
      "en-US": "String operations: split/join/replace/substring/contains/trim/case/length.",
    },
    inputs: {
      operation: { label: { "zh-CN": "\u64cd\u4f5c", "en-US": "Operation" } },
      value: { label: { "zh-CN": "\u8f93\u5165\u6587\u672c", "en-US": "Value" } },
      items: { label: { "zh-CN": "\u8f93\u5165\u6570\u7ec4", "en-US": "Items" } },
      delimiter: { label: { "zh-CN": "\u5206\u9694\u7b26", "en-US": "Delimiter" } },
      joiner: { label: { "zh-CN": "\u8fde\u63a5\u7b26", "en-US": "Joiner" } },
      search: { label: { "zh-CN": "\u67e5\u627e", "en-US": "Search" } },
      replace_with: { label: { "zh-CN": "\u66ff\u6362\u4e3a", "en-US": "Replace With" } },
      start: { label: { "zh-CN": "\u8d77\u59cb\u4e0b\u6807", "en-US": "Start" } },
      end: { label: { "zh-CN": "\u7ed3\u675f\u4e0b\u6807", "en-US": "End" } },
      case_sensitive: { label: { "zh-CN": "\u533a\u5206\u5927\u5c0f\u5199", "en-US": "Case Sensitive" } },
    },
    outputs: {
      result: { label: { "zh-CN": "\u7ed3\u679c", "en-US": "Result" } },
      text: { label: { "zh-CN": "\u6587\u672c\u7ed3\u679c", "en-US": "Text" } },
      items: { label: { "zh-CN": "\u6570\u7ec4\u7ed3\u679c", "en-US": "Items" } },
      contains: { label: { "zh-CN": "\u5305\u542b\u7ed3\u679c", "en-US": "Contains" } },
      length: { label: { "zh-CN": "\u957f\u5ea6", "en-US": "Length" } },
    },
  },
  ui: {
    icon: "type",
    color: "#60a5fa",
    group: "Utility",
  },
  runtime: {
    execution: "local",
    sideEffects: false,
    allowNetwork: false,
  },
  compatibility: {
    engineVersion: ">=0.1.0",
  },
};
