import type { ModularActionDefinition } from "../../modularActions";

export const definition: ModularActionDefinition = {
  id: "string_ops",
  version: "1.0.0",
  name: "String Ops",
  description: "String operations: split/join/replace/substring/contains/trim/case/length.",
  category: "utility",
  tags: ["string", "transform"],
  inputs: [
    {
      name: "operation",
      type: "string",
      default: "split",
      options: [
        { value: "split", label: "split" },
        { value: "join", label: "join" },
        { value: "replace", label: "replace" },
        { value: "substring", label: "substring" },
        { value: "contains", label: "contains" },
        { value: "trim", label: "trim" },
        { value: "to_upper", label: "to_upper" },
        { value: "to_lower", label: "to_lower" },
        { value: "length", label: "length" },
      ],
      description: "Operation type.",
    },
    {
      name: "value",
      type: "string",
      default: "",
      description: "Source value.",
    },
    {
      name: "items",
      type: "string",
      default: "",
      description: "Optional array input for join (supports array or JSON string).",
    },
    {
      name: "delimiter",
      type: "string",
      default: ",",
      description: "Delimiter used by split (and CSV fallback for join).",
    },
    {
      name: "joiner",
      type: "string",
      default: ",",
      description: "Join separator.",
    },
    {
      name: "search",
      type: "string",
      default: "",
      description: "Search text for replace/contains.",
    },
    {
      name: "replace_with",
      type: "string",
      default: "",
      description: "Replacement text for replace.",
    },
    {
      name: "start",
      type: "integer",
      default: 0,
      description: "Start index for substring.",
    },
    {
      name: "end",
      type: "integer",
      default: -1,
      description: "End index for substring. -1 means to end.",
    },
    {
      name: "case_sensitive",
      type: "boolean",
      default: true,
      description: "Whether replace/contains is case-sensitive.",
    },
  ],
  outputs: [
    { name: "result", type: "any", description: "Operation result." },
    { name: "text", type: "string", description: "String representation result." },
    { name: "items", type: "any", description: "Array result, when applicable." },
    { name: "contains", type: "boolean", description: "Contains check result." },
    { name: "length", type: "integer", description: "String/array length." },
  ],
  i18n: {
    name: { "zh-CN": "字符串处理", "en-US": "String Ops" },
    description: {
      "zh-CN": "字符串操作：split/join/replace/substring/contains 等。",
      "en-US": "String operations: split/join/replace/substring/contains/trim/case/length.",
    },
    inputs: {
      operation: { label: { "zh-CN": "操作", "en-US": "Operation" } },
      value: { label: { "zh-CN": "输入文本", "en-US": "Value" } },
      items: { label: { "zh-CN": "输入数组", "en-US": "Items" } },
      delimiter: { label: { "zh-CN": "分隔符", "en-US": "Delimiter" } },
      joiner: { label: { "zh-CN": "连接符", "en-US": "Joiner" } },
      search: { label: { "zh-CN": "查找", "en-US": "Search" } },
      replace_with: { label: { "zh-CN": "替换为", "en-US": "Replace With" } },
      start: { label: { "zh-CN": "起始下标", "en-US": "Start" } },
      end: { label: { "zh-CN": "结束下标", "en-US": "End" } },
      case_sensitive: { label: { "zh-CN": "区分大小写", "en-US": "Case Sensitive" } },
    },
    outputs: {
      result: { label: { "zh-CN": "结果", "en-US": "Result" } },
      text: { label: { "zh-CN": "文本结果", "en-US": "Text" } },
      items: { label: { "zh-CN": "数组结果", "en-US": "Items" } },
      contains: { label: { "zh-CN": "包含结果", "en-US": "Contains" } },
      length: { label: { "zh-CN": "长度", "en-US": "Length" } },
    },
  },
  ui: {
    icon: "type",
    color: "#60a5fa",
    group: "Utility",
  },
  runtime: {
    execution: "local",
    sideEffects: false,
    allowNetwork: false,
  },
  compatibility: {
    engineVersion: ">=0.1.0",
  },
};